DATA SEGMENT
MAXLEN    DB   100
DATA   ENDS
CODE SEGMENT
ASSUME CS:CODE,DS:DATA
START:MOV AX,DATA
      MOV DS,AX
      LEA DX,MAXLEN
      MOV AH,10
      INT 21H
      MOV DL,10
      MOV AH,2
      INT 21H
      
      LEA DX,MAXLEN+2
      MOV AH,9
      INT 21H
      MOV AH,4CH
      INT 21H
CODE ENDS 
      END START